#!/usr/bin/env python3
"""Generate web/src/components/generatedToolbarIcons.ts from
assets/runebender-icons.ufo.

Workflow: design/edit the icon glyphs in Runebender (open the UFO),
save, then run this script and rebuild the web bundle. Each UFO glyph
becomes one entry in TOOLBAR_ICONS keyed by glyph name; the toolbar
maps tool ids to glyph names.

UFOs are Y-up; SVG is Y-down — we flip Y when emitting the path. Each
icon carries its own tight bounding box as the viewBox so the toolbar's
xMidYMid-meet scaling renders every icon at a uniform size, centered
(matching runebender-xilem's paint_icon), regardless of how the glyph
is positioned in the em.

Run with an interpreter that has fontTools + ufoLib2, e.g. the ComfyUI
venv:
    /Users/eli/Work/comfy/repos/ComfyUI/.venv/bin/python \
        scripts/build_toolbar_icons.py
"""

from __future__ import annotations

import json
from pathlib import Path

import ufoLib2
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

# UFO (Y-up) -> SVG (Y-down).
UFO_TO_SVG = (1, 0, 0, -1, 0, 0)


def _fmt(value: float) -> str:
    """Compact number: drop trailing .0 so integer coords stay integers."""
    rounded = round(value, 2)
    if rounded == int(rounded):
        return str(int(rounded))
    return str(rounded)


def load_icon_codepoints(repo_root: Path) -> dict[str, int]:
    path = repo_root / "assets" / "runebender-icons.codepoints.json"
    return {
        name: int(str(value).removeprefix("U+"), 16)
        for name, value in json.loads(path.read_text(encoding="utf-8")).items()
    }


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    ufo_path = repo_root / "assets" / "runebender-icons.ufo"
    out_path = repo_root / "web" / "src" / "components" / "generatedToolbarIcons.ts"
    if not ufo_path.exists():
        raise SystemExit(
            f"{ufo_path} not found — run scripts/bootstrap_icons_ufo.py first."
        )

    font = ufoLib2.Font.open(ufo_path)
    icon_codepoints = load_icon_codepoints(repo_root)

    entries: list[tuple[int, str, str, str, str]] = []
    for glyph in font:
        mode = glyph.lib.get("com.runebender.iconRenderMode", "fill")
        bounds_pen = BoundsPen(font)
        glyph.draw(TransformPen(bounds_pen, UFO_TO_SVG))
        if bounds_pen.bounds is None:
            continue  # empty glyph, skip
        x_min, y_min, x_max, y_max = bounds_pen.bounds
        if mode == "stroke":
            x_min -= 2
            y_min -= 2
            x_max += 2
            y_max += 2
        view_box = (
            f"{_fmt(x_min)} {_fmt(y_min)} "
            f"{_fmt(x_max - x_min)} {_fmt(y_max - y_min)}"
        )
        svg_pen = SVGPathPen(font)
        glyph.draw(TransformPen(svg_pen, UFO_TO_SVG))
        codepoint = icon_codepoints.get(
            glyph.name,
            glyph.unicodes[0] if glyph.unicodes else 0x110000,
        )
        entries.append((codepoint, glyph.name, view_box, svg_pen.getCommands(), mode))

    entries.sort(key=lambda e: (e[0], e[1]))

    lines = [
        "// AUTO-GENERATED by scripts/build_toolbar_icons.py from",
        "// assets/runebender-icons.ufo — do not edit by hand.",
        "// To change an icon: open the UFO in Runebender, edit, save, then",
        "// re-run the script and rebuild the web bundle.",
        "",
        "export interface ToolbarIcon {",
        "  /** Tight bounding box of the outline in SVG (Y-down) space. */",
        "  viewBox: string;",
        "  /** SVG path data for the icon outline. */",
        "  d: string;",
        '  /** Fill closed outlines, or stroke open/path icons. Defaults to "fill". */',
        '  mode?: "fill" | "stroke";',
        "}",
        "",
        "/** Icon geometry keyed by UFO glyph name. */",
        "export const TOOLBAR_ICONS: Record<string, ToolbarIcon> = {",
    ]
    for _codepoint, name, view_box, d, mode in entries:
        key = repr(name)
        mode_text = f', mode: "{mode}"' if mode == "stroke" else ""
        lines.append(f'  {key}: {{ viewBox: "{view_box}", d: "{d}"{mode_text} }},')
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} with {len(entries)} icons: "
          f"{', '.join(e[1] for e in entries)}")


if __name__ == "__main__":
    main()
